spring:
  main:
    web-application-type: reactive
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cjx
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 6009
