spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketingOnline
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 6008